import { NextResponse } from "next/server";

import { isAuthenticated } from "@/app/lib/adminAuth";
import {
  getAnalyticsDb,
  getAnalyticsPeriod,
  loadEvents,
  periodCreatedAtFilter,
  publicPeriod,
  type BehaviourEvent,
} from "@/app/lib/userAnalytics";

export const dynamic = "force-dynamic";

/** Account & profile pages (not orders, wishlist or notifications). */
const ACCOUNT_PATH = /^\/account(?:\/|$)/i;

interface FeatureDefinition {
  key: string;
  label: string;
  /** What one "use" means — shown in the admin. */
  description: string;
  events: { event: string; label: string }[];
  matches?: (event: BehaviourEvent) => boolean;
}

/**
 * Every event listed here is generated by the store:
 *   browser  → page_view, product_view, search, cart_add, cart_remove,
 *              checkout_start, coupon_apply, product_share,
 *              notification_open, notification_click, support_open
 *   server   → wishlist_add, wishlist_remove (wishlist API),
 *              review_submit (reviews API), purchase (checkout API)
 */
const FEATURES: FeatureDefinition[] = [
  {
    key: "wishlist",
    label: "Wishlist",
    description: "Products saved to or removed from the wishlist.",
    events: [
      { event: "wishlist_add", label: "added" },
      { event: "wishlist_remove", label: "removed" },
    ],
  },
  {
    key: "search",
    label: "Search",
    description: "Searches run from the search overlay.",
    events: [{ event: "search", label: "searches" }],
  },
  {
    key: "cart",
    label: "Cart",
    description:
      "Bag additions / quantity increases and removals (emptying the bag after an order is not counted).",
    events: [
      { event: "cart_add", label: "added" },
      { event: "cart_remove", label: "removed" },
    ],
  },
  {
    key: "coupons",
    label: "Coupons",
    description: "Coupon codes successfully applied at checkout.",
    events: [{ event: "coupon_apply", label: "applied" }],
  },
  {
    key: "sharing",
    label: "Product sharing",
    description: "Product links shared (share sheet) or copied from a product page.",
    events: [{ event: "product_share", label: "shared" }],
  },
  {
    key: "notifications",
    label: "Notifications",
    description: "Notifications page opened and notifications clicked.",
    events: [
      { event: "notification_open", label: "opened" },
      { event: "notification_click", label: "clicked" },
    ],
  },
  {
    key: "reviews",
    label: "Reviews",
    description: "Product reviews submitted.",
    events: [{ event: "review_submit", label: "submitted" }],
  },
  {
    key: "support",
    label: "Support",
    description: "Help & Support page opened or WhatsApp order help clicked.",
    events: [{ event: "support_open", label: "opened" }],
  },
  {
    key: "account",
    label: "Account / profile",
    description: "Signed-in visits to /account and /account/reviews.",
    events: [{ event: "page_view", label: "page views" }],
    matches: (event) => ACCOUNT_PATH.test(event.path),
  },
  {
    key: "checkout",
    label: "Checkout",
    description: "Checkouts started and orders placed.",
    events: [
      { event: "checkout_start", label: "started" },
      { event: "purchase", label: "orders placed" },
    ],
  },
];

/**
 * GET /api/admin/user-engagement/feature-usage?range=30d
 * Uses, unique customers and unique sessions per store feature.
 */
export async function GET(request: Request) {
  try {
    if (!(await isAuthenticated())) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const period = getAnalyticsPeriod(
      new URL(request.url).searchParams.get("range")
    );
    const db = await getAnalyticsDb();

    const trackedEvents = [
      ...new Set(FEATURES.flatMap((feature) => feature.events.map((item) => item.event))),
    ];

    const events = await loadEvents(
      db,
      { ...periodCreatedAtFilter(period), event: { $in: trackedEvents } },
      { event: 1, userId: 1, sessionId: 1, path: 1, createdAt: 1 }
    );

    const features = FEATURES.map((feature) => {
      const names = new Set(feature.events.map((item) => item.event));
      const selected = events.filter(
        (event) =>
          names.has(event.event) && (!feature.matches || feature.matches(event))
      );

      const users = new Set(selected.map((event) => event.userId).filter(Boolean));
      const sessions = new Set(
        selected.map((event) => event.sessionId).filter(Boolean)
      );

      return {
        key: feature.key,
        label: feature.label,
        description: feature.description,
        uses: selected.length,
        uniqueUsers: users.size,
        uniqueSessions: sessions.size,
        /** Uses recorded before server events carried a session id. */
        usesWithoutSession: selected.filter((event) => !event.sessionId).length,
        breakdown: feature.events.map((item) => ({
          event: item.event,
          label: item.label,
          count: selected.filter((event) => event.event === item.event).length,
        })),
      };
    });

    return NextResponse.json({
      period: publicPeriod(period),
      features,
      totalEvents: events.length,
    });
  } catch (error) {
    console.error("[ADMIN FEATURE USAGE]", error);
    return NextResponse.json(
      { error: "Unable to load feature usage." },
      { status: 500 }
    );
  }
}
